version: '2'
services:
  app:
    image: saxelsso/demo:latest
    ports:
    - "8080:8080"
    links:
    - app-db
  app-db:
    image: postgres:latest
    container_name: app-db
    expose:
    - "5432"
    environment:
    - POSTGRES_PASSWORD=postgres

